In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.21.5


In [4]:
data_1 = [5, 9, 2.5, 3, 1]
array_1 = np.array(data_1)

In [5]:
print(array_1)

[5.  9.  2.5 3.  1. ]


In [6]:
data_2 = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
array_2 = np.array(data_2)

In [7]:
print(array_2)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [8]:
print(array_2.ndim)
print(array_2.shape)

2
(2, 5)


In [9]:
print(array_1.dtype)
print(array_2.dtype)

float64
int32


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((2, 3, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5, 30, 3)  # 시작 값, 종료 값, 단계 지정

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [15]:
array_1 = np.array([1, 3, 5, 7, 9], dtype=np.float32)
array_2 = np.array([1, 3, 5, 7, 9], dtype=np.int16)

In [16]:
array_1.dtype

dtype('float32')

In [17]:
array_2.dtype

dtype('int16')

In [18]:
array_2_float = array_2.astype(np.float64)
array_2_float.dtype

dtype('float64')

In [19]:
num_strings = np.array(['-3.15', '5', '8.4', '21', '-12'], dtype=np.string_)
num_strings.dtype

dtype('S5')

In [20]:
num_strings = num_strings.astype(float)   # float 대신 np.float64 입력 가능
num_strings

array([ -3.15,   5.  ,   8.4 ,  21.  , -12.  ])

In [21]:
num_strings.dtype

dtype('float64')

In [22]:
array_1 = np.array([[1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.]])
array_2 = np.array([[1., 3., 5., 7., 9.], [2., 4., 6., 8., 10.]])

In [23]:
array_1 * array_2

array([[  1.,   6.,  15.,  28.,  45.],
       [ 12.,  28.,  48.,  72., 100.]])

In [24]:
array_1 - array_2

array([[ 0., -1., -2., -3., -4.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [25]:
1 / array_1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [26]:
array_2 ** 0.25

array([[1.        , 1.31607401, 1.49534878, 1.62657656, 1.73205081],
       [1.18920712, 1.41421356, 1.56508458, 1.68179283, 1.77827941]])

In [27]:
array_1 > array_2

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False]])

In [28]:
array_1d = np.arange(15)
array_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
array_1d[7]

7

In [30]:
array_1d[[7, 9]]

array([7, 9])

In [31]:
array_1d[4:7]

array([4, 5, 6])

In [32]:
array_1d[4:7] = 10
array_1d

array([ 0,  1,  2,  3, 10, 10, 10,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
array_2d = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])
array_2d

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [34]:
array_2d[1]

array([3, 6, 9])

In [35]:
array_2d[1][2]   # array_2d[1, 2] 형식으로 써도 됨

9

In [36]:
array_2d[:2]

array([[2, 4, 6],
       [3, 6, 9]])

In [37]:
array_2d[:2, :2]

array([[2, 4],
       [3, 6]])

In [38]:
array_2d[[0, 1], :2]

array([[2, 4],
       [3, 6]])

In [39]:
array_2d[:, :1]

array([[2],
       [3],
       [4]])

In [40]:
np.random.seed(1000)

In [41]:
np.random.rand(5)

array([0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454])

In [42]:
np.random.rand(10)

array([0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072,
       0.20708234, 0.74246953, 0.39215413, 0.18225652, 0.74353941])

In [43]:
np.random.randn(10)

array([-0.4122031 , -0.07400906, -0.92893693,  1.39006147,  1.19506933,
        0.70734239,  0.99296211,  0.13946394, -0.08988248, -0.14974264])

In [44]:
np.random.randn(5, 3)

array([[ 0.4055338 , -0.75133127,  0.93131848],
       [-0.24745023, -0.27072883, -1.27939856],
       [-1.07900875, -0.08796666,  2.05225999],
       [-1.23931612,  1.10970741, -1.15768513],
       [ 0.09870641, -1.4651006 , -1.75193341]])

In [45]:
np.random.randint(10, size=15)

array([9, 6, 2, 9, 5, 8, 5, 6, 9, 6, 7, 6, 3, 4, 8])

In [46]:
np.random.randint(5, 25, size=10)

array([ 6,  8, 18, 18, 18, 12, 23,  5,  9, 19])

In [47]:
np.random.randint(5, 25, size=(3, 8))

array([[22, 10, 18,  6, 22, 12,  9, 21],
       [ 7,  5, 17, 16, 15, 20, 13,  5],
       [24,  5,  8,  8, 16,  8, 11,  9]])

In [48]:
np.random.normal(size=(5, 3))

array([[ 1.96503337, -1.03030175,  1.57129952],
       [-0.21905672,  0.39413675,  0.07549162],
       [-0.29327772,  2.04332521,  0.67261267],
       [ 0.81063734,  1.9887597 , -0.27364058],
       [-0.58071803,  0.55071837,  1.05656617]])

In [49]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.random.shuffle(data)

In [51]:
data

array([7, 3, 9, 5, 1, 6, 2, 4, 8, 0])

In [52]:
np.random.choice(10, 5, replace=False)

array([9, 4, 8, 5, 3])

In [53]:
np.random.choice(10, 5, replace=True)

array([6, 4, 6, 8, 1])

In [91]:
np.random.choice(3, 12, p=[0.3, 0.6, 0.1]) #p는 총합이 1이어야 함

array([0, 2, 1, 0, 2, 1, 1, 0, 1, 2, 1, 0])

In [90]:
np.random.choice(['apple', 'banana', 'orange'], 8)

array(['apple', 'apple', 'apple', 'orange', 'apple', 'apple', 'orange',
       'apple'], dtype='<U6')

In [56]:
array = np.random.randint(30, size=20)
array

array([12, 26,  5,  3, 18, 12,  5,  3,  7,  3, 11, 13, 28,  4, 25, 20, 10,
       10,  0, 22])

In [57]:
len(array)

20

In [58]:
np.mean(array)

11.85

In [59]:
array.mean()

11.85

In [60]:
np.median(array)

10.5

In [61]:
np.std(array)

8.380184962159246

In [62]:
np.var(array)

70.22749999999998

In [63]:
np.min(array)

0

In [64]:
np.max(array)

28

In [65]:
array.sum()

237

In [66]:
array.cumsum()

array([ 12,  38,  43,  46,  64,  76,  81,  84,  91,  94, 105, 118, 146,
       150, 175, 195, 205, 215, 215, 237], dtype=int32)

In [67]:
array.cumprod()

array([         12,         312,        1560,        4680,       84240,
           1010880,     5054400,    15163200,   106142400,   318427200,
        -792268096, -1709550656,  -622778112,  1803854848,  2146698240,
         -15708160,  -157081600, -1570816000,           0,           0],
      dtype=int32)

In [68]:
np.percentile(array, 0)

0.0

In [69]:
np.percentile(array, 25)

4.75

In [70]:
np.percentile(array, 50)

10.5

In [71]:
np.percentile(array, 75)

18.5

In [72]:
np.percentile(array, 100)

28.0

In [73]:
array = np.random.randn(50)

In [74]:
(array > 0).sum()

20

In [75]:
bools = np.array([1, 1, 0, 0])
bools

array([1, 1, 0, 0])

In [76]:
bools.any()

True

In [77]:
bools.all()

False

In [78]:
array = np.random.randint(20, size=10)
array

array([14,  3, 19,  6, 16, 19,  7, 17, 14, 14])

In [79]:
array.sort()

In [80]:
array

array([ 3,  6,  7, 14, 14, 14, 16, 17, 19, 19])

In [81]:
fruits = np.array(['apple', 'banana', 'kiwi', 'apple', 'kiwi', 'lemon', 'banana', 'lemon'])
fruits

array(['apple', 'banana', 'kiwi', 'apple', 'kiwi', 'lemon', 'banana',
       'lemon'], dtype='<U6')

In [82]:
np.unique(fruits)

array(['apple', 'banana', 'kiwi', 'lemon'], dtype='<U6')

In [83]:
sorted(set(fruits))

['apple', 'banana', 'kiwi', 'lemon']

In [84]:
numbers = np.array([5 ,7, 1, 2, 1, 7, 8, 5])
numbers

array([5, 7, 1, 2, 1, 7, 8, 5])

In [85]:
np.unique(numbers)

array([1, 2, 5, 7, 8])

In [86]:
numbers_2 = np.array([1, 4, 6, 9, 2, 3, 5, 1])
numbers_2

array([1, 4, 6, 9, 2, 3, 5, 1])

In [87]:
np.intersect1d(numbers, numbers_2)

array([1, 2, 5])