In [1]:
!pip install JEDI

Defaulting to user installation because normal site-packages is not writeable


In [2]:
x = [1, 2, 3]
y = x
print(y)

[1, 2, 3]


In [3]:
x.append(4) # x가 가리키는 리스트에 4를 추가
print(y)

[1, 2, 3, 4]


In [4]:
x = 7.5
print(x.real, "+", x.imag, 'i')

7.5 + 0.0 i


In [5]:
x = 7.5
x.is_integer()

False

In [6]:
x = 7.0
x.is_integer()

True

In [7]:
type(x.is_integer)

builtin_function_or_method

In [8]:
x = 10
type(x)

int

In [9]:
x = 0.000005
y = 5e-6
print(x == y)

True


In [10]:
x = 1400000.00
y = 1.4e6
print(x == y)

True


In [11]:
A = '문자열을 만들어 봐요!'
B = "문자열은 이렇게 만들 수도 있어요~"
print(A, B)

문자열을 만들어 봐요! 문자열은 이렇게 만들 수도 있어요~


In [12]:
case1 = (5 < 10)
case1
type(case1)

bool

In [13]:
print(True, False)

True False


In [14]:
float(10)

10.0

In [15]:
s = '5.6328'
type(s)

str

In [16]:
f_value = float(s)
type(f_value)

float

In [17]:
int(f_value)

5

In [18]:
f_value = print('apple')
print(f_value)

apple
None


In [19]:
list_a = [1, 3, 5, None]
print(list_a)

[1, 3, 5, None]


In [20]:
tup = ('apple', 'orange', 'banana')
print(tup)
list_b = list(tup)
print(list_b)

('apple', 'orange', 'banana')
['apple', 'orange', 'banana']


In [21]:
len(list_b)

3

In [22]:
list_c = [1, 'apple', 5.76, 3, 7, [2, 4, 6, 8]]
print(list_c)

[1, 'apple', 5.76, 3, 7, [2, 4, 6, 8]]


In [23]:
list_d = [1, 3, 5, 7, 9, 2, 4, 6, 8, 10]
print(list_d[0])
print(list_d[2])

1
5


In [24]:
print(list_d[-1])
print(list_d[-3])

10
6


In [25]:
print(list_d[2:6])
print(list_d[-6:-2])

[5, 7, 9, 2]
[9, 2, 4, 6]


In [26]:
t = (1, 2, 3)
print(t)
t = 1, 2, 3
print(t)

(1, 2, 3)
(1, 2, 3)


In [27]:
a, b = 3, 5
print(a)
print(b)

3
5


In [28]:
b, a = a, b
print(a)
print(b)

5
3


In [29]:
tup = (1, 4, 3, 3, 2, 2, 5, 1, 1)
tup.count(1)

3

In [30]:
nums = {'one' : 1, 'two' : 2, 'three' : 3}
print(nums)

keys = nums.keys()
values = nums.values()
print(keys, values)

{'one': 1, 'two': 2, 'three': 3}
dict_keys(['one', 'two', 'three']) dict_values([1, 2, 3])


In [31]:
nums['two']

2

In [32]:
nums['four'] = 'some value'
print(nums)

{'one': 1, 'two': 2, 'three': 3, 'four': 'some value'}


In [33]:
set([1, 1, 1, 2, 3, 3,])

{1, 2, 3}

In [34]:
{1, 1, 1, 2, 3, 3}

{1, 2, 3}

In [36]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8,}

In [37]:
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [39]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [40]:
a & b

{3, 4, 5}

In [41]:
a.intersection(b)

{3, 4, 5}

In [42]:
x = 3

if x < 0 :
    print('음수군요.')
elif x == 0 :
    print('0과 같군요.')
elif 0 < x < 5 :
    print('양수이지만 5보다는 작군요.')
else :
    print('양수이지만 5와 같거나 크네요.')

양수이지만 5보다는 작군요.


In [46]:
for n in [1, 3, 5, 7, 9] :
    print(n, end = '')

13579

In [47]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [49]:
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

In [50]:
num = 0

for i in range(1, 21, 2):
    num = num + 1
print(num)

10


In [51]:
nums = [-8, 32, 7, -1, 15, 51]   # 숫자 리스트 정의

i = 0 
for num in nums: 
    i = i + 1 
    if num < 0 : 
        print('%d번째 숫자는 음수.' %i)
    elif 0 < num < 20 :
        print('%d번째 숫자는 양수이지만 20보다는 작다.' %i)
    elif 21 < num < 40 :
        print('%d번째 숫자는 양수이지만 40보다는 작다.' %i)
    else: 
        print('%d번째 숫자는 양수이고 50보다 크다.' %i)

1번째 숫자는 음수.
2번째 숫자는 양수이지만 40보다는 작다.
3번째 숫자는 양수이지만 20보다는 작다.
4번째 숫자는 음수.
5번째 숫자는 양수이지만 20보다는 작다.
6번째 숫자는 양수이고 50보다 크다.


In [52]:
result = []
for i in range(10) :
    result.append(i * 2)
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [53]:
[i * 2 for i in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [54]:
text = ['am', 'banana', 'car', 'dark', 'drink', 'effect']
[x.upper() for x in text if len(x) > 3]

['BANANA', 'DARK', 'DRINK', 'EFFECT']

In [60]:
result = []
for n in range(10) :
    result.append(n * 2)
print(result, end = '')

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [61]:
text_length = {len(x) for x in text}
text_length

{2, 3, 4, 5, 6}

In [62]:
set(map(len, text))

{2, 3, 4, 5, 6}

In [63]:
tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
simple_list = [x for tup in tuples for x in tup]
print(simple_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [64]:
items = [0, 5, 10, 15, 20]
for i in range(len(items)) :
    print(i, items[i])

0 0
1 5
2 10
3 15
4 20


In [66]:
for i, v in enumerate(items) :
    print(i,v)

0 0
1 5
2 10
3 15
4 20


In [67]:
li_1 = [0, 5, 10, 15, 20]
li_2 = [5, 25, 125, 256, 512]
for i, v in zip(li_1, li_2) :
    print(i, v)

0 5
5 25
10 125
15 256
20 512


In [68]:
sorted([9, 3, 1, 6, 8, 2, 5, 4, 7, 0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
sorted('Happy day!')

[' ', '!', 'H', 'a', 'a', 'd', 'p', 'p', 'y', 'y']

In [70]:
def plus(a, b):
    total = a + b
    return total

In [71]:
plus(5, 8)

13

In [73]:
def multiplication(a, b, c=5) :
    return a * b * c
multiplication(2, 4)

40

In [74]:
def show() :
    a = 5
    b = 3
    c = 7
    return a, b, c
show()

(5, 3, 7)

In [75]:
func_1 = lambda x: x * 3
li_1 = [2, 4, 6, 8, 10]
list(map(func_1, li_1))

[6, 12, 18, 24, 30]

In [76]:
import numpy as np
import pandas as pd
import seaborn as sns

In [77]:
data_1 = [5, 9, 2.5, 3, 1]
array_1 = np.array(data_1)
array_1

array([5. , 9. , 2.5, 3. , 1. ])

In [78]:
data_2 = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
array_2 = np.array(data_2)
data_2

[[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]

In [79]:
print(array_2.ndim)
print(array_2.shape)

2
(2, 5)


In [80]:
print(array_1.dtype)
print(array_2.dtype)

float64
int32


In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.arange(5, 30, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [85]:
array_1 = np.array([1, 3, 5, 7, 9], dtype = np.float32)
array_2 = np.array([1, 3, 5, 7, 9], dtype = np.int16)

In [86]:
array_1.dtype

dtype('float32')

In [87]:
array_2.dtype

dtype('int16')

In [88]:
num_strings = np.array(['-3.15', '5', '8.4', '21', '-12'], dtype = np.string_)
num_strings.dtype

dtype('S5')

In [89]:
num_strings = num_strings.astype(float) 
num_strings

array([ -3.15,   5.  ,   8.4 ,  21.  , -12.  ])

In [90]:
num_strings.dtype #float64 실수형, S5 string 글씨

dtype('float64')

In [91]:
array_1 = np.array([[1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.]])
array_2 = np.array([[1., 3., 5., 7., 9.], [2., 4., 6., 8., 10.]])

In [92]:
array_1 * array_2

array([[  1.,   6.,  15.,  28.,  45.],
       [ 12.,  28.,  48.,  72., 100.]])

In [93]:
array_1 - array_2

array([[ 0., -1., -2., -3., -4.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [94]:
1/array_1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [95]:
array_2 ** 0.25

array([[1.        , 1.31607401, 1.49534878, 1.62657656, 1.73205081],
       [1.18920712, 1.41421356, 1.56508458, 1.68179283, 1.77827941]])

In [96]:
array_1 > array_2

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False]])