In [1]:
mid_scores = [10, 20, 30]   
final_scores = [70, 80, 90]

In [2]:
total = mid_scores + final_scores 
total

[10, 20, 30, 70, 80, 90]

In [4]:
import numpy as np  

mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])

total = mid_scores + final_scores
print('시험성적 합 :', total) 
print('시험성적 평균 :', total/2) 

시험성적의 합계 : [ 70  90 110]
시험성적의 평균 : [35. 45. 55.]


In [6]:
import numpy as np
a = np.array([1, 2, 3])    
a.shape 

(3,)

In [7]:
a.ndim

1

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [12]:
import numpy as np

array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1번 : array_a =', array_a)

array_b = np.array(range(10))
print('2번 : array_b =', array_b)

array_c = np.array(range(0,10,2))
print('3번 : array_c =', array_c)

print('\n4번 : ')
print('array_c의 shape :', array_c.shape)
print('array_c의 ndim :', array_c.ndim)
print('array_c의 ctype :', array_c.dtype)
print('array_c의 size :', array_c.size)
print('array_c의 itemsize :',array_c.itemsize)

1번 : array_a = [0 1 2 3 4 5 6 7 8 9]
2번 : array_b = [0 1 2 3 4 5 6 7 8 9]
3번 : array_c = [0 2 4 6 8]

4번 : 
array_c의 shape : (5,)
array_c의 ndim : 1
array_c의 ctype : int32
array_c의 size : 5
array_c의 itemsize : 4


In [13]:
import numpy as np
salary = np.array([220, 250, 230])

salary = salary + 100
print(salary)

[320 350 330]


In [14]:
salary = np.array([220, 250, 230])
salary = salary * 2
print(salary)

[440 500 460]


In [15]:
salary = np.array([220, 250, 230]) 
salary = salary * 2.1 
print(salary)

[462. 525. 483.]


In [16]:
tangled = np.array([ 100, 'test', 3.0, False])
print(tangled)

['100' 'test' '3.0' 'False']


In [17]:
import numpy as np

heights = [ 1.83, 1.76, 1.69, 1.86, 1.77, 1.73 ]
weights = [ 86,    74,    59,   95,    80,   68  ]

np_heights = np.array(heights)
np_weights = np.array(weights)

bmi = np_weights/(np_heights**2)
print(bmi)

[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


In [18]:
np_array = np.array([[ 1,  2,  3,  4], 
                     [ 5,  6,  7,  8], 
                     [ 9, 10, 11, 12], 
                     [13, 14, 15, 16]]) 
print(np_array[::2][::2])
print(np_array[::2,::2]) 

[[1 2 3 4]]
[[ 1  3]
 [ 9 11]]


In [19]:
import numpy as np 
 
players = np.zeros( (100, 3) ) 
players[:, 0] = 10 * np.random.randn(100) + 175 
players[:, 1] = 10 * np.random.randn(100) + 70
players[:, 2] = np.floor(10 * np.random.randn(100)) + 22

heights = players[:, 0] 
print('신장 평균값:', np.mean(heights))
print('신장 중앙값:', np.median(heights))

weights = players[:, 1] 
print('체중 평균값:', np.mean(weights))
print('체중 중앙값:', np.median(weights))

ages = players[:, 2] 
print('나이 평균값:', np.mean(ages))
print('나이 중앙값:', np.median(ages))

신장 평균값: 175.79485041693061
신장 중앙값: 176.15221669711627
체중 평균값: 69.74317086871659
체중 중앙값: 70.65587847287146
나이 평균값: 22.62
나이 중앙값: 22.0
